# Generated by Django 6.0.6 on 2026-07-16 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='max_distance',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum preferred distance in kilometres.', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='payment_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferences_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_gender',
            field=models.CharField(blank=True, choices=[('female', 'Female'), ('male', 'Male')], max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_max_age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_min_age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='relationship_type',
            field=models.CharField(blank=True, choices=[('friendship', 'Friendship'), ('relationship', 'Relationship')], max_length=20),
        ),
    ]
